import SwiftUI

struct LyricsSheet: View {
    @EnvironmentObject private var playback: PlaybackController
    @Environment(\.dismiss) private var dismiss
    @State private var selected: CaptionTrack?
    @State private var text = ""
    @State private var isLoading = false
    @State private var errorMessage: String?

    var body: some View {
        NavigationStack {
            Group {
                if playback.captionTracks.isEmpty {
                    ContentUnavailableView(
                        "No lyrics / captions",
                        systemImage: "text.bubble",
                        description: Text("This video has no caption tracks from the extractor.")
                    )
                } else {
                    VStack(spacing: 0) {
                        Picker("Language", selection: $selected) {
                            ForEach(playback.captionTracks) { track in
                                Text(track.displayName + (track.isAutoGenerated ? " (auto)" : ""))
                                    .tag(Optional(track))
                            }
                        }
                        .pickerStyle(.menu)
                        .padding()

                        if isLoading {
                            ProgressView("Loading…")
                                .frame(maxWidth: .infinity, maxHeight: .infinity)
                        } else if let errorMessage {
                            Text(errorMessage)
                                .foregroundStyle(.red)
                                .padding()
                            Spacer()
                        } else {
                            ScrollView {
                                Text(text.isEmpty ? "—" : text)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                    .padding()
                                    .textSelection(.enabled)
                            }
                        }
                    }
                }
            }
            .navigationTitle("Lyrics")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Close") { dismiss() }
                }
            }
            .onAppear {
                if selected == nil {
                    selected = CaptionService.pickDefault(playback.captionTracks)
                }
            }
            .onChange(of: selected?.id) { _, _ in
                Task { await load() }
            }
            .task {
                await load()
            }
        }
    }

    private func load() async {
        guard let track = selected ?? CaptionService.pickDefault(playback.captionTracks) else { return }
        selected = track
        isLoading = true
        errorMessage = nil
        defer { isLoading = false }
        if let vtt = await CaptionService.fetchVtt(track: track) {
            text = CaptionService.plainText(from: vtt)
            if text.isEmpty {
                errorMessage = "Caption track was empty"
            }
        } else {
            errorMessage = "Failed to load captions"
            text = ""
        }
    }
}
