import SwiftUI

/// In-page lyrics panel (shared by sheet and player detail tab).
struct LyricsPanel: View {
    @EnvironmentObject private var playback: PlaybackController
    @State private var selected: CaptionTrack?
    @State private var text = ""
    @State private var isLoading = false
    @State private var errorMessage: String?

    var body: some View {
        Group {
            if playback.captionTracks.isEmpty {
                Text("No lyrics / captions available for this video.")
                    .font(.subheadline)
                    .foregroundStyle(YTLiteColor.onSurfaceVariant)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.vertical, 24)
            } else {
                VStack(alignment: .leading, spacing: 12) {
                    Picker("Language", selection: $selected) {
                        ForEach(playback.captionTracks) { track in
                            Text(track.displayName + (track.isAutoGenerated ? " (auto)" : ""))
                                .tag(Optional(track))
                        }
                    }
                    .pickerStyle(.menu)
                    .tint(YTLiteColor.accent)

                    if isLoading {
                        ProgressView()
                            .tint(YTLiteColor.accent)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 24)
                    } else if let errorMessage {
                        Text(errorMessage)
                            .foregroundStyle(.red)
                    } else {
                        Text(text.isEmpty ? "—" : text)
                            .font(.body)
                            .foregroundStyle(.white)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .textSelection(.enabled)
                    }
                }
            }
        }
        .onAppear {
            if selected == nil {
                selected = CaptionService.pickDefault(playback.captionTracks)
            }
        }
        .onChange(of: selected?.id) { _, _ in
            Task { await load() }
        }
        .onChange(of: playback.nowPlaying?.videoId) { _, _ in
            selected = CaptionService.pickDefault(playback.captionTracks)
            Task { await load() }
        }
        .task { await load() }
    }

    private func load() async {
        guard let track = selected ?? CaptionService.pickDefault(playback.captionTracks) else {
            text = ""
            return
        }
        selected = track
        isLoading = true
        errorMessage = nil
        defer { isLoading = false }
        if let vtt = await CaptionService.fetchVtt(track: track) {
            text = CaptionService.plainText(from: vtt)
            if text.isEmpty {
                errorMessage = "Caption track was empty"
            }
        } else {
            errorMessage = "Failed to load captions"
            text = ""
        }
    }
}

struct LyricsSheet: View {
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            LyricsPanel()
                .padding()
                .navigationTitle("Lyrics")
                .navigationBarTitleDisplayMode(.inline)
                .toolbar {
                    ToolbarItem(placement: .cancellationAction) {
                        Button("Close") { dismiss() }
                    }
                }
                .background(YTLiteColor.background)
        }
        .preferredColorScheme(.dark)
    }
}
