package com.ytlite.player.data.model

import androidx.compose.runtime.Immutable

@Immutable
data class CaptionTrack(
    val languageCode: String,
    val displayName: String,
    val baseUrl: String,
    val isAutoGenerated: Boolean = false,
)
