import SwiftUI

/// Lyrics overlay that can load captions for any video (not only now playing).
struct TrackLyricsSheet: View {
    let videoId: String
    @Environment(\.dismiss) private var dismiss

    @State private var tracks: [CaptionTrack] = []
    @State private var selected: CaptionTrack?
    @State private var text = ""
    @State private var isLoading = true
    @State private var errorMessage: String?

    var body: some View {
        NavigationStack {
            Group {
                if isLoading {
                    ProgressView()
                        .tint(YTLiteColor.accent)
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else if tracks.isEmpty {
                    Text(errorMessage ?? "No lyrics / captions available for this video.")
                        .font(YTLiteType.body)
                        .foregroundStyle(YTLiteColor.onSurfaceVariant)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding()
                } else {
                    VStack(alignment: .leading, spacing: YTLiteLayout.stackLoose) {
                        Picker("Language", selection: $selected) {
                            ForEach(tracks) { track in
                                Text(track.displayName + (track.isAutoGenerated ? " (auto)" : ""))
                                    .tag(Optional(track))
                            }
                        }
                        .pickerStyle(.menu)
                        .tint(YTLiteColor.accent)

                        if let errorMessage {
                            Text(errorMessage)
                                .font(YTLiteType.body)
                                .foregroundStyle(YTLiteColor.danger)
                        }

                        ScrollView {
                            Text(text.isEmpty ? "—" : text)
                                .font(YTLiteType.body)
                                .foregroundStyle(YTLiteColor.onSurface)
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .textSelection(.enabled)
                        }
                    }
                    .padding(YTLiteLayout.screenPadding)
                }
            }
            .background(YTLiteColor.background)
            .navigationTitle("Lyrics")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Close") { dismiss() }
                }
            }
            .task { await loadTracks() }
            .onChange(of: selected?.id) { _, _ in
                Task { await loadText() }
            }
        }
    }

    private func loadTracks() async {
        isLoading = true
        errorMessage = nil
        defer { isLoading = false }
        do {
            let playback = try await ExtractorBridge.shared.extractPlayback(videoId: videoId)
            tracks = playback.captionTracks
            selected = CaptionService.pickDefault(tracks)
            await loadText()
            if tracks.isEmpty {
                errorMessage = "No lyrics / captions available for this video."
            }
        } catch {
            errorMessage = error.localizedDescription
            tracks = []
        }
    }

    private func loadText() async {
        guard let track = selected ?? CaptionService.pickDefault(tracks) else {
            text = ""
            return
        }
        selected = track
        if let vtt = await CaptionService.fetchVtt(track: track) {
            text = CaptionService.plainText(from: vtt)
            if text.isEmpty {
                errorMessage = "Caption track was empty"
            } else {
                errorMessage = nil
            }
        } else {
            errorMessage = "Failed to load captions"
            text = ""
        }
    }
}
