package com.ytlite.player.data.js

import android.util.Log
import com.ytlite.player.data.model.FeedPage
import com.ytlite.player.data.model.VideoItem
import com.ytlite.player.data.model.CaptionTrack
import com.ytlite.player.data.model.StreamFormat
import com.ytlite.player.data.model.VideoPlayback
import org.json.JSONArray
import org.json.JSONObject

object JsResultMapper {

    private const val TAG = "JsResultMapper"

    private val SKIPPED_TYPES = setOf(
        "reelShelfRenderer",
        "adVideoRenderer",
        "promotedSparklesWebRenderer",
        "displayAdRenderer",
    )

    fun toFeedPage(message: JSONObject): FeedPage? {
        // createSearchMsg(r, searchApiResult) puts the SearchApi payload directly in message.data
        val payload = message.optJSONObject("data") ?: run {
            Log.w(TAG, "toFeedPage: missing data object")
            return null
        }

        if (!payload.optBoolean("success", false)) {
            Log.w(
                TAG,
                "toFeedPage: success=false code=${payload.optInt("errorCode", -1)} " +
                    "isReady=${payload.optBoolean("isReady")}",
            )
            return null
        }

        val items = payload.optJSONArray("data") ?: JSONArray()
        Log.d(TAG, "toFeedPage: raw items=${items.length()}")

        val videos = ArrayList<VideoItem>(items.length())
        for (index in 0 until items.length()) {
            val item = items.optJSONObject(index) ?: continue
            val type = item.optString("type")
            if (type in SKIPPED_TYPES || type.contains("ad", ignoreCase = true)) continue
            if (type != "compactVideoRenderer" && type != "gridVideoRenderer") {
                if (index < 3) Log.d(TAG, "skip type=$type")
                continue
            }
            val data = item.optJSONObject("data") ?: continue
            mapSearchItem(data)?.let { videos.add(it) }
        }

        val continuation = payload.optString("next").takeIf { it.isNotBlank() }
        if (videos.isEmpty()) {
            Log.w(TAG, "toFeedPage: mapped 0 videos from ${items.length()} items")
            return null
        }
        Log.d(TAG, "toFeedPage: mapped ${videos.size} videos")
        return FeedPage(
            videos = videos.distinctBy { it.videoId },
            continuation = continuation,
        )
    }

    fun toVideoPlayback(message: JSONObject): VideoPlayback? {
        val envelope = message.optJSONObject("data") ?: return null
        if (!envelope.optBoolean("success", false)) return null

        val payload = envelope.optJSONObject("data") ?: return null
        val music = payload.optJSONObject("music") ?: return null
        val videoId = music.optString("videoId")
            .ifBlank { payload.optString("url").let(::extractVideoIdFromUrl) }
        if (videoId.isBlank()) return null

        val formats = mapFormats(music.optJSONArray("formats"))
        if (formats.isEmpty()) return null

        return VideoPlayback(
            videoId = videoId,
            title = music.optString("title"),
            description = music.optString("description"),
            channelName = music.optString("uploader"),
            channelId = music.optString("channelID"),
            formats = formats,
            durationSeconds = music.optString("duration").toLongOrNull() ?: 0L,
            viewCount = music.optString("viewCount").toLongOrNull() ?: 0L,
            captionTracks = mapCaptionTracks(music),
        )
    }

    fun mapCaptionTracks(music: JSONObject): List<CaptionTrack> {
        val tracks = LinkedHashMap<String, CaptionTrack>()
        collectCaptionMaps(music.optJSONObject("subtitles"), tracks, isAuto = false)
        collectCaptionMaps(music.optJSONObject("automatic_captions"), tracks, isAuto = true)
        val rendererTracks = music.optJSONArray("captionTracks")
        if (rendererTracks != null) {
            for (index in 0 until rendererTracks.length()) {
                val track = rendererTracks.optJSONObject(index) ?: continue
                val baseUrl = track.optString("baseUrl")
                    .ifBlank { track.optString("url") }
                if (baseUrl.isBlank()) continue
                val languageCode = track.optString("languageCode")
                    .ifBlank { track.optString("vssId").removePrefix(".") }
                    .ifBlank { "und" }
                val displayName = track.optJSONObject("name")?.optString("simpleText")
                    ?.ifBlank { track.optString("name") }
                    ?: languageCode
                tracks.putIfAbsent(
                    languageCode,
                    CaptionTrack(
                        languageCode = languageCode,
                        displayName = displayName,
                        baseUrl = baseUrl,
                        isAutoGenerated = track.optBoolean("isTranslatable", false),
                    ),
                )
            }
        }
        return tracks.values.toList()
    }

    private fun collectCaptionMaps(
        map: JSONObject?,
        out: LinkedHashMap<String, CaptionTrack>,
        isAuto: Boolean,
    ) {
        if (map == null) return
        val keys = map.keys()
        while (keys.hasNext()) {
            val languageCode = keys.next()
            val entries = map.optJSONArray(languageCode) ?: continue
            for (index in 0 until entries.length()) {
                val entry = entries.optJSONObject(index) ?: continue
                val url = entry.optString("url")
                if (url.isBlank()) continue
                val displayName = entry.optString("name").ifBlank { languageCode }
                out.putIfAbsent(
                    "$languageCode-$isAuto",
                    CaptionTrack(
                        languageCode = languageCode,
                        displayName = displayName,
                        baseUrl = url,
                        isAutoGenerated = isAuto,
                    ),
                )
                break
            }
        }
    }

    fun mapFormats(formats: JSONArray?): List<StreamFormat> {
        if (formats == null || formats.length() == 0) return emptyList()

        val mapped = (0 until formats.length()).mapNotNull { index ->
            val format = formats.optJSONObject(index) ?: return@mapNotNull null
            val url = format.optString("url")
            if (url.isBlank()) return@mapNotNull null

            val itag = format.optInt("itag")
            val mimeType = format.optString("type").ifBlank { format.optString("mimeType") }
            val acodec = normalizeCodec(format.optString("acodec"))
            val vcodec = normalizeCodec(format.optString("vcodec"))
            var hasAudio = acodec.isNotBlank()
            var hasVideo = vcodec.isNotBlank()
            // Known AAC audio-only itags must never be treated as video, even if codecs are missing.
            if (com.ytlite.player.data.model.StreamFormatIds.isAudioOnlyItag(itag)) {
                hasAudio = true
                hasVideo = false
            } else if (mimeType.lowercase().startsWith("audio/")) {
                hasAudio = true
                hasVideo = false
            }

            StreamFormat(
                itag = itag,
                width = format.optInt("width"),
                height = format.optInt("height"),
                hasAudio = hasAudio,
                hasVideo = hasVideo,
                url = url,
                mimeType = mimeType,
                contentLengthBytes = parseContentLength(format, url),
                bitrateBps = format.optLong("bitrate").takeIf { it > 0 }
                    ?: format.optString("bitrate").toLongOrNull()
                    ?: format.optLong("averageBitrate").takeIf { it > 0 }
                    ?: format.optString("averageBitrate").toLongOrNull()
                    ?: 0L,
            )
        }

        return mapped.sortedWith(
            compareByDescending<StreamFormat> { it.hasVideo && it.hasAudio }
                .thenByDescending { it.height },
        )
    }

    private fun normalizeCodec(codec: String): String {
        val trimmed = codec.trim()
        return if (trimmed.isEmpty() || trimmed.equals("none", ignoreCase = true)) {
            ""
        } else {
            trimmed
        }
    }

    private fun parseContentLength(format: JSONObject, url: String): Long {
        val fromKeys = sequenceOf(
            "filesize",
            "contentLength",
            "content_length",
            "filesize_approx",
        ).mapNotNull { key ->
            format.optLong(key).takeIf { it > 0 }
                ?: format.optString(key).toLongOrNull()?.takeIf { it > 0 }
        }.firstOrNull()
        if (fromKeys != null) return fromKeys

        return runCatching {
            android.net.Uri.parse(url).getQueryParameter("clen")?.toLongOrNull()?.takeIf { it > 0 }
        }.getOrNull() ?: 0L
    }

    fun playbackErrorMessage(message: JSONObject): String? {
        val envelope = message.optJSONObject("data") ?: return null
        val payload = envelope.optJSONObject("data")
        return envelope.optString("errorMsg")
            .ifBlank { envelope.optString("errorMSG") }
            .ifBlank { payload?.optString("errMsg").orEmpty() }
            .ifBlank { payload?.optString("errorMSG").orEmpty() }
            .ifBlank {
                if (payload?.optJSONObject("music") == null) {
                    "Unable to extract playable stream"
                } else {
                    ""
                }
            }
            .removePrefix("__notRetry@")
            .takeIf { it.isNotBlank() }
    }

    fun errorMessage(message: JSONObject): String? {
        val payload = message.optJSONObject("data")
        if (payload == null) {
            return message.optString("errorMsg").takeIf { it.isNotBlank() }
        }

        val errorCode = payload.optInt("errorCode", -1)
        return payload.optString("errorMsg")
            .ifBlank { payload.optString("errorMSG") }
            .ifBlank { payload.optString("errMsg") }
            .ifBlank {
                if (!payload.optBoolean("success", true) && errorCode > 0) {
                    "Search failed (HTTP $errorCode)"
                } else {
                    ""
                }
            }
            .ifBlank {
                if (!payload.optBoolean("success", true)) {
                    "YouTube search returned no results"
                } else {
                    ""
                }
            }
            .takeIf { it.isNotBlank() }
    }

    private fun mapSearchItem(data: JSONObject): VideoItem? {
        val videoId = data.optString("videoId")
        if (videoId.isBlank()) return null

        val title = data.optString("title")
        if (title.isBlank()) return null

        val thumbnailUrl = pickThumbnailUrl(data.optJSONArray("thumbnails"))
            ?: "https://i.ytimg.com/img/no_thumbnail.jpg"
        return VideoItem(
            videoId = videoId,
            title = title,
            channelName = data.optString("author").ifBlank { "Unknown" },
            channelId = null,
            thumbnailUrl = thumbnailUrl,
            durationText = data.optString("lengthText").ifBlank { null },
            viewCountText = data.optString("shortViewCountText")
                .ifBlank { data.optString("viewCountText").ifBlank { null } },
            publishedTimeText = data.optString("publishedTime").ifBlank { null },
        )
    }

    private fun pickThumbnailUrl(thumbnails: JSONArray?): String? {
        if (thumbnails == null || thumbnails.length() == 0) return null
        return thumbnails.optJSONObject(thumbnails.length() - 1)?.optString("url")?.takeIf { it.isNotBlank() }
    }

    private fun extractVideoIdFromUrl(url: String): String {
        val match = VIDEO_ID_REGEX.find(url) ?: return ""
        return match.groupValues[1]
    }

    private val VIDEO_ID_REGEX = Regex("(?:v=|/)([0-9A-Za-z_-]{11})")
}
