import Foundation

struct CaptionTrack: Identifiable, Hashable, Sendable {
    var id: String { languageCode + (isAutoGenerated ? "-auto" : "") }
    let languageCode: String
    let displayName: String
    let baseURL: String
    let isAutoGenerated: Bool
}

enum CaptionService {
    static func pickDefault(_ tracks: [CaptionTrack], preferred: String = "en") -> CaptionTrack? {
        tracks.first { $0.languageCode.caseInsensitiveCompare(preferred) == .orderedSame }
            ?? tracks.first { $0.languageCode.lowercased().hasPrefix(preferred.lowercased()) }
            ?? tracks.first
    }

    static func fetchVtt(track: CaptionTrack) async -> String? {
        var urlString = track.baseURL
        if !urlString.contains("fmt=") {
            urlString += urlString.contains("?") ? "&fmt=vtt" : "?fmt=vtt"
        }
        guard let url = URL(string: urlString) else { return nil }
        let result = await YouTubeHTTPClient.shared.request(
            url: url.absoluteString,
            method: "GET",
            headers: ["User-Agent": YouTubeConstants.userAgent],
            body: nil
        )
        guard result.success, !result.body.isEmpty else { return nil }
        return result.body
    }

    /// Very small VTT → plain lines (cues text only).
    static func plainText(from vtt: String) -> String {
        let lines = vtt.components(separatedBy: .newlines)
        var out: [String] = []
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { continue }
            if trimmed.hasPrefix("WEBVTT") { continue }
            if trimmed.contains("-->") { continue }
            if trimmed.allSatisfy({ $0.isNumber || $0 == ":" || $0 == "." }) { continue }
            let cleaned = trimmed
                .replacingOccurrences(of: "<[^>]+>", with: "", options: .regularExpression)
            if !cleaned.isEmpty {
                out.append(cleaned)
            }
        }
        return out.joined(separator: "\n")
    }
}
